name: Static Tests

on: [pull_request]

jobs:
  static-tests:
    name: Static Tests

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Unit test
        run: npm test

      - name: ES lint
        run: npm run lint

      - name: Commit lint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: 'commitlint.config.js'
